{"errorType":"ServiceException","errorMessage":"An error occurred and the request cannot be processed.","trace":["ServiceException: An error occurred and the request cannot be processed.","    at de_ServiceExceptionRes (/var/task/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:4512:21)","    at de_CommandError (/var/task/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:3962:19)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20","    at async /var/task/node_modules/@smithy/core/dist-cjs/index.js:167:18","    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38","    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22","    at async callLambdaSyncWithoutRetry (/var/task/node_modules/@remotion/lambda-client/dist/call-lambda-sync.js:8:17)","    at async Object.callFunctionSyncImplementation [as callFunctionSync] (/var/task/node_modules/@remotion/lambda-client/dist/call-lambda-sync.js:22:17)","    at async getRenderProgress (/var/task/node_modules/@remotion/lambda-client/dist/get-render-progress.js:36:20)"]}